// <auto-generated />
using System;
using Dynamic.Fidelity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicApi.Migrations.Fidelity
{
    [DbContext(typeof(DynamicFidelityDbContext))]
    [Migration("20260418110542_InitialFidelityPoints")]
    partial class InitialFidelityPoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.Points", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentBalance")
                        .HasColumnType("int");

                    b.Property<int>("ExpiredBalance")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastEarnedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastMovementAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("LastReference")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("LastSpentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PendingBalance")
                        .HasColumnType("int");

                    b.Property<int>("TotalEarned")
                        .HasColumnType("int");

                    b.Property<int>("TotalSpent")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "NegocioId")
                        .IsUnique();

                    b.ToTable("fidelity_points", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
