// <auto-generated />
using System;
using Dynamic.Fidelity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicApi.Migrations.Fidelity
{
    [DbContext(typeof(DynamicFidelityDbContext))]
    [Migration("20260628094304_AddPromotionCampaignTicketSourceToFidelity")]
    partial class AddPromotionCampaignTicketSourceToFidelity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PendingTicketAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activated")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("AssignedTicketId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QrCampaignId")
                        .HasColumnType("char(36)");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("TicketTemplateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Activated");

                    b.HasIndex("QrCampaignId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "QrCampaignId")
                        .IsUnique();

                    b.ToTable("fidelity_pending_ticket_assignments", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.Points", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentBalance")
                        .HasColumnType("int");

                    b.Property<int>("ExpiredBalance")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastEarnedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastMovementAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("LastReference")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("LastSpentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PendingBalance")
                        .HasColumnType("int");

                    b.Property<int>("TotalEarned")
                        .HasColumnType("int");

                    b.Property<int>("TotalSpent")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "NegocioId")
                        .IsUnique();

                    b.ToTable("fidelity_points", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PointsOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AmountEuros")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CompletedTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExpectedPoints")
                        .HasColumnType("int");

                    b.Property<int>("MaxValidationAttempts")
                        .HasColumnType("int");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("RatioSnapshot")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ValidatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ValidatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ValidationAttempts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.HasIndex("UserId", "NegocioId", "Status");

                    b.ToTable("fidelity_points_operations", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PointsOperationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("AttemptedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("CancelledOperation")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("NegocioId");

                    b.HasIndex("OperationId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("fidelity_points_operation_attempts", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PointsTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("AmountEuros")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<int>("BalanceBefore")
                        .HasColumnType("int");

                    b.Property<string>("CounterpartyUserCodeSnapshot")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid?>("CounterpartyUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PointsAmount")
                        .HasColumnType("int");

                    b.Property<Guid?>("PointsId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Reference")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("UserCodeSnapshot")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ValidatorUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartyUserId");

                    b.HasIndex("NegocioId");

                    b.HasIndex("OperationId");

                    b.HasIndex("UserId", "NegocioId", "CreatedAtUtc");

                    b.ToTable("fidelity_points_transactions", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.QrCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("AvailableFromUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("Expira")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LandingPath")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("UnSoloUsoPorUsuario")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("WelcomeTicketTemplateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Activa");

                    b.HasIndex("NegocioId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("fidelity_qr_campaigns", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("AvailableFromUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BeneficioEspecialDetalle")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("BeneficioEspecialResumen")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CategoriaEnvioEspecial")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)");

                    b.Property<string>("CodigoInterno")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CodigoVisible")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CondicionesUso")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<decimal?>("DescuentoImporteFijo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("DescuentoPorcentaje")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<bool>("EsDeUnSoloUso")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsPlantilla")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("GastoMinimoRequerido")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("InstruccionesCanje")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("MaxUsosPorCliente")
                        .HasColumnType("int");

                    b.Property<string>("MensajeMarketing")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("NotasInternas")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid?>("ParentTicketId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Publicado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("PuntosCoste")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereValidacionManual")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("SourcePromotionCampaignId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SourcePromotionRecipientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SourceQrCampaignId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TituloCanje")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Usado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UsedByEmployeeReference")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UsedInStoreReference")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("UsosConsumidos")
                        .HasColumnType("int");

                    b.Property<int?>("ValidezDiasDesdeAsignacion")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaEnvioEspecial");

                    b.HasIndex("EsPlantilla");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("NegocioId");

                    b.HasIndex("ParentTicketId");

                    b.HasIndex("SourcePromotionCampaignId");

                    b.HasIndex("SourcePromotionRecipientId")
                        .IsUnique();

                    b.HasIndex("Tipo");

                    b.HasIndex("Usado");

                    b.HasIndex("UserId");

                    b.HasIndex("NegocioId", "CodigoVisible");

                    b.HasIndex("NegocioId", "UserId");

                    b.ToTable("fidelity_tickets", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.UserCodeDirectoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserCode")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("fidelity_user_codes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
