// <auto-generated />
using System;
using Dynamic.Fidelity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicApi.Migrations.Fidelity
{
    [DbContext(typeof(DynamicFidelityDbContext))]
    partial class DynamicFidelityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PendingTicketAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activated")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("AssignedTicketId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QrCampaignId")
                        .HasColumnType("char(36)");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("TicketTemplateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Activated");

                    b.HasIndex("QrCampaignId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "QrCampaignId")
                        .IsUnique();

                    b.ToTable("fidelity_pending_ticket_assignments", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.Points", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentBalance")
                        .HasColumnType("int");

                    b.Property<int>("ExpiredBalance")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastEarnedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastMovementAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("LastReference")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("LastSpentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PendingBalance")
                        .HasColumnType("int");

                    b.Property<int>("TotalEarned")
                        .HasColumnType("int");

                    b.Property<int>("TotalSpent")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "NegocioId")
                        .IsUnique();

                    b.ToTable("fidelity_points", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PointsGroupAccrual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AmountEuros")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkerUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("fidelity_points_group_accruals", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PointsGroupAccrualRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GroupAccrualId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PointsAssigned")
                        .HasColumnType("int");

                    b.Property<int>("ScanOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("GroupAccrualId", "UserId")
                        .IsUnique();

                    b.ToTable("fidelity_points_group_accrual_recipients", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PointsOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AmountEuros")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CompletedTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExpectedPoints")
                        .HasColumnType("int");

                    b.Property<int>("MaxValidationAttempts")
                        .HasColumnType("int");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("RatioSnapshot")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ValidatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ValidatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ValidationAttempts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.HasIndex("UserId", "NegocioId", "Status");

                    b.ToTable("fidelity_points_operations", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PointsOperationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("AttemptedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("CancelledOperation")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("NegocioId");

                    b.HasIndex("OperationId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("fidelity_points_operation_attempts", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PointsSplit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<int>("OriginalPoints")
                        .HasColumnType("int");

                    b.Property<int>("OwnerShare")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SourceTransactionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SourceTransactionId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "CreatedAtUtc");

                    b.ToTable("fidelity_points_splits", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PointsSplitRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IncomingTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PointsAmount")
                        .HasColumnType("int");

                    b.Property<Guid>("SplitId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IncomingTransactionId")
                        .IsUnique();

                    b.HasIndex("SplitId", "UserId")
                        .IsUnique();

                    b.ToTable("fidelity_points_split_recipients", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PointsTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("AmountEuros")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<int>("BalanceBefore")
                        .HasColumnType("int");

                    b.Property<int?>("BasePointsSnapshot")
                        .HasColumnType("int");

                    b.Property<decimal?>("BaseRatioSnapshot")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("BenefitMultiplierSnapshot")
                        .HasPrecision(30, 28)
                        .HasColumnType("decimal(30,28)");

                    b.Property<Guid?>("ClientOperationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CounterpartyUserCodeSnapshot")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid?>("CounterpartyUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PointsAmount")
                        .HasColumnType("int");

                    b.Property<Guid?>("PointsId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("RecurrenceSnapshotJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Reference")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("UserCodeSnapshot")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ValidatorUserId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("VisitOrdinalSnapshot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartyUserId");

                    b.HasIndex("NegocioId");

                    b.HasIndex("OperationId");

                    b.HasIndex("NegocioId", "ClientOperationId")
                        .IsUnique();

                    b.HasIndex("UserId", "NegocioId", "CreatedAtUtc");

                    b.ToTable("fidelity_points_transactions", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.QrCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("AvailableFromUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("Expira")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LandingPath")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("UnSoloUsoPorUsuario")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("WelcomeTicketTemplateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Activa");

                    b.HasIndex("NegocioId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("fidelity_qr_campaigns", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.RecurrenceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("BenefitDays")
                        .HasColumnType("int");

                    b.Property<string>("BenefitMode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<int?>("BenefitVisits")
                        .HasColumnType("int");

                    b.Property<string>("Compatibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<int?>("MaxActivationsPerCustomer")
                        .HasColumnType("int");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("WindowDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId", "Active", "Priority");

                    b.ToTable("fidelity_recurrence_rules", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("AvailableFromUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BeneficioEspecialDetalle")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("BeneficioEspecialResumen")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CategoriaEnvioEspecial")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)");

                    b.Property<string>("CodigoInterno")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CodigoVisible")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CondicionesUso")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<decimal?>("DescuentoImporteFijo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("DescuentoPorcentaje")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<bool>("EsDeUnSoloUso")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsPlantilla")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("GastoMinimoRequerido")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("InstruccionesCanje")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("MaxUsosPorCliente")
                        .HasColumnType("int");

                    b.Property<string>("MensajeMarketing")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("NotasInternas")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid?>("ParentTicketId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Publicado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("PuntosCoste")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereValidacionManual")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("SourcePromotionCampaignId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SourcePromotionRecipientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SourceQrCampaignId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TituloCanje")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Usado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UsedByEmployeeReference")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UsedInStoreReference")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("UsosConsumidos")
                        .HasColumnType("int");

                    b.Property<int?>("ValidezDiasDesdeAsignacion")
                        .HasColumnType("int");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaEnvioEspecial");

                    b.HasIndex("EsPlantilla");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("NegocioId");

                    b.HasIndex("ParentTicketId");

                    b.HasIndex("SourcePromotionCampaignId");

                    b.HasIndex("SourcePromotionRecipientId")
                        .IsUnique();

                    b.HasIndex("Tipo");

                    b.HasIndex("Usado");

                    b.HasIndex("UserId");

                    b.HasIndex("NegocioId", "CodigoVisible");

                    b.HasIndex("NegocioId", "UserId");

                    b.ToTable("fidelity_tickets", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.TicketRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("FinalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool?>("MinimumSpendSatisfied")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ParentTicketId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("PurchaseAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("SourcePromotionCampaignId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SourcePromotionRecipientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SourceQrCampaignId")
                        .HasColumnType("char(36)");

                    b.Property<string>("StoreReference")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TicketCategoriaSnapshot")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)");

                    b.Property<string>("TicketCodeSnapshot")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TicketNombreSnapshot")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("TicketTipoSnapshot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("UsageNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ValidatedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("NegocioId");

                    b.HasIndex("ParentTicketId");

                    b.HasIndex("SourcePromotionCampaignId");

                    b.HasIndex("SourcePromotionRecipientId");

                    b.HasIndex("SourceQrCampaignId");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.HasIndex("ValidatedByUserId");

                    b.HasIndex("NegocioId", "CreatedAtUtc");

                    b.HasIndex("TicketId", "UsageNumber")
                        .IsUnique();

                    b.ToTable("fidelity_ticket_redemptions", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.UserCodeDirectoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserCode")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("fidelity_user_codes", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.WelcomeTicketClaim", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "NegocioId");

                    b.ToTable("fidelity_welcome_ticket_claims", (string)null);
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PointsGroupAccrualRecipient", b =>
                {
                    b.HasOne("Dynamic.Fidelity.Domain.Entities.PointsGroupAccrual", "GroupAccrual")
                        .WithMany("Recipients")
                        .HasForeignKey("GroupAccrualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupAccrual");
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PointsSplitRecipient", b =>
                {
                    b.HasOne("Dynamic.Fidelity.Domain.Entities.PointsSplit", "Split")
                        .WithMany("Recipients")
                        .HasForeignKey("SplitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Split");
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PointsGroupAccrual", b =>
                {
                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("Dynamic.Fidelity.Domain.Entities.PointsSplit", b =>
                {
                    b.Navigation("Recipients");
                });
#pragma warning restore 612, 618
        }
    }
}
