// <auto-generated />
using System;
using Dynamic.Reports.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicApi.Migrations.Reports
{
    [DbContext(typeof(DynamicReportsDbContext))]
    [Migration("20260721183850_InitialReports")]
    partial class InitialReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Dynamic.Reports.Domain.Entities.ReportEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Message")
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<Guid?>("NewAssignedAdminUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NewPriority")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<Guid?>("PreviousAssignedAdminUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PreviousPriority")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId", "CreatedAtUtc");

                    b.ToTable("support_report_events", (string)null);
                });

            modelBuilder.Entity("Dynamic.Reports.Domain.Entities.SupportReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid?>("AssignedAdminUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<DateTime?>("OccurredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid?>("PromotionCampaignId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ResolvedByAdminUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("PromotionCampaignId");

                    b.HasIndex("TicketId");

                    b.HasIndex("AssignedAdminUserId", "Status");

                    b.HasIndex("ReporterUserId", "CreatedAtUtc");

                    b.HasIndex("Status", "Priority", "CreatedAtUtc");

                    b.ToTable("support_reports", (string)null);
                });

            modelBuilder.Entity("Dynamic.Reports.Domain.Entities.ReportEvent", b =>
                {
                    b.HasOne("Dynamic.Reports.Domain.Entities.SupportReport", "Report")
                        .WithMany("Events")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Dynamic.Reports.Domain.Entities.SupportReport", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
