// <auto-generated />
using Dynamic.Users.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DynamicApi.Migrations
{
    [DbContext(typeof(DynamicUsersDbContext))]
    [Migration("20260621090000_AddTemporaryPasswordFlag")]
    public partial class AddTemporaryPasswordFlag
    {
    }
}
