// <auto-generated />
using Dynamic.Users.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DynamicApi.Migrations
{
    [DbContext(typeof(DynamicUsersDbContext))]
    [Migration("20260620110000_AddPasswordResetFlow")]
    public partial class AddPasswordResetFlow
    {
    }
}
