// <auto-generated />
using System;
using Dynamic.Negocios.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicApi.Migrations.Negocios
{
    [DbContext(typeof(DynamicNegociosDbContext))]
    partial class DynamicNegociosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Dynamic.Negocios.Domain.Entities.Negocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("BonoBienvenidaTicketId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("CaducidadPuntosDias")
                        .HasColumnType("int");

                    b.Property<string>("CategoriaPrincipal")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ClaveMaestraLocalHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("ClaveMaestraLocalUpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CodigoInterno")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("ColorAcento")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ColorFondo")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ColorPrimario")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ColorSecundario")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ColorTexto")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("CondicionesUsoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescripcionCorta")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DescripcionLarga")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("DescripcionProgramaFidelizacion")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("DiasFestivosJson")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("DireccionLinea1")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DireccionLinea2")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DocumentoFiscal")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("DominioPersonalizado")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmailContacto")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("EmailSoporte")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Eslogan")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Etiquetas")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("FechaFinSuscripcionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInicioSuscripcionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaPublicacionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FuenteCuerpo")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("FuenteTitulo")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("GaleriaImagenesJson")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("HeadlinePortal")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HistoriaMarca")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("HorarioAperturaJson")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("IconoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("IdiomaPorDefecto")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("IdiomasSoportados")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ImagenCoverUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("ImagenHeroUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("ImagenMobileUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("LogoPrincipalUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("LogoSecundarioUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<int?>("MaximoClientesRegistrados")
                        .HasColumnType("int");

                    b.Property<int?>("MaximoUbicaciones")
                        .HasColumnType("int");

                    b.Property<int?>("MaximoUsuariosBackoffice")
                        .HasColumnType("int");

                    b.Property<string>("MensajeBienvenida")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("MensajeLegal")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Mision")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("MonedaCodigo")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("NombreProgramaFidelizacion")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<bool>("OcultarMarcaGeneral")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OpenGraphImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PaisCodigoIso2")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<bool>("PermiteCampanasAutomatizadas")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PermiteNotificacionesEmail")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PermiteNotificacionesPush")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PermiteNotificacionesSms")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PermiteProgramaReferidos")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PermiteQrCheckIn")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PermiteRegistroPublico")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PermiteWalletPass")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PersonaObjetivo")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("PlanSuscripcion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PoliticaCookiesUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PoliticaPrivacidadUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("PublicadoPortal")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("PuntosBienvenida")
                        .HasColumnType("int");

                    b.Property<int?>("PuntosCumpleanos")
                        .HasColumnType("int");

                    b.Property<decimal?>("RatioConversionEurosAPuntos")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("ReferenciaExterna")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Region")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("RegistroMercantil")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("RequiereAprobacionManualClientes")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RutaPortal")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SeoKeywords")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SitioWebUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SlugPortal")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Subcategoria")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("SubheadlinePortal")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TelefonoPrincipal")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TelefonoSecundario")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TextoCondicionesPrograma")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("TextoPoliticaPuntos")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("TikTokUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("TipoNegocio")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("ValorMonetarioPunto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Valores")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("VideoPromocionalUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Vision")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("XUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("YoutubeUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("ZonaHoraria")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("BonoBienvenidaTicketId");

                    b.HasIndex("Estado");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("SlugPortal")
                        .IsUnique();

                    b.ToTable("negocios", (string)null);
                });

            modelBuilder.Entity("Dynamic.Negocios.Domain.Entities.NegocioUsuarioVinculacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaAceptacionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaFinUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInicioUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInvitacionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LinkedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NotasInternas")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("OrigenVinculacion")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("PuedeAccederBackoffice")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeGestionarCampanas")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeGestionarClientes")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeGestionarNegocio")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeGestionarPuntos")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeValidarTickets")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeVerReportes")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TipoVinculacion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TituloRelacion")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid?>("UnlinkedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Activa");

                    b.HasIndex("TipoVinculacion");

                    b.HasIndex("UserId");

                    b.HasIndex("NegocioId", "UserId")
                        .IsUnique();

                    b.ToTable("negocio_user_links", (string)null);
                });

            modelBuilder.Entity("Dynamic.Negocios.Domain.Entities.NegocioUsuarioVinculacion", b =>
                {
                    b.HasOne("Dynamic.Negocios.Domain.Entities.Negocio", "Negocio")
                        .WithMany("VinculacionesUsuarios")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Dynamic.Negocios.Domain.Entities.Negocio", b =>
                {
                    b.Navigation("VinculacionesUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
